version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: historia_clinica
      POSTGRES_USER: hc_user
      POSTGRES_PASSWORD: hc_password_dev_2025
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hc_user -d historia_clinica"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hc_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: hc_postgres_data
  pgadmin_data:
    name: hc_pgadmin_data
