# fly.toml app configuration file
# Documentación: https://fly.io/docs/reference/configuration/

app = "hc-app"
primary_region = "gru"  # São Paulo (más cercano a Argentina)

[build]

[env]
  PORT = "8080"
  APP_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
