"""add medical studies table

Revision ID: 86f029a95caf
Revises: cf4acbd721e1
Create Date: 2025-10-18 00:45:48.017473

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86f029a95caf"
down_revision: Union[str, None] = "cf4acbd721e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medical_studies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("consultation_id", sa.Integer(), nullable=True),
        sa.Column("study_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("study_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("study_date", sa.Date(), nullable=False),
        sa.Column("institution", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("requesting_doctor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("results", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("observations", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("diagnosis", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("file_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("is_pending", sa.Boolean(), nullable=False),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.Column("requires_followup", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medical_studies_consultation_id"),
        "medical_studies",
        ["consultation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medical_studies_patient_id"), "medical_studies", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_medical_studies_study_date"), "medical_studies", ["study_date"], unique=False
    )
    op.create_index(
        op.f("ix_medical_studies_study_name"), "medical_studies", ["study_name"], unique=False
    )
    op.create_index(
        op.f("ix_medical_studies_study_type"), "medical_studies", ["study_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_medical_studies_study_type"), table_name="medical_studies")
    op.drop_index(op.f("ix_medical_studies_study_name"), table_name="medical_studies")
    op.drop_index(op.f("ix_medical_studies_study_date"), table_name="medical_studies")
    op.drop_index(op.f("ix_medical_studies_patient_id"), table_name="medical_studies")
    op.drop_index(op.f("ix_medical_studies_consultation_id"), table_name="medical_studies")
    op.drop_table("medical_studies")
    # ### end Alembic commands ###
