"""Initial migration: patients, consultations, medications

Revision ID: cf4acbd721e1
Revises:
Create Date: 2025-10-17 23:53:05.660334

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cf4acbd721e1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("dni", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("blood_type", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("allergies", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("chronic_conditions", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("family_history", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_dni"), "patients", ["dni"], unique=True)
    op.create_index(op.f("ix_patients_first_name"), "patients", ["first_name"], unique=False)
    op.create_index(op.f("ix_patients_last_name"), "patients", ["last_name"], unique=False)
    op.create_table(
        "consultations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("consultation_date", sa.DateTime(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("symptoms", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("diagnosis", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("treatment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("blood_pressure", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("heart_rate", sa.Integer(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("next_visit", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consultations_consultation_date"),
        "consultations",
        ["consultation_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consultations_patient_id"), "consultations", ["patient_id"], unique=False
    )
    op.create_table(
        "medications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("consultation_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("dosage", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("frequency", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("duration", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_chronic", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medications_consultation_id"), "medications", ["consultation_id"], unique=False
    )
    op.create_index(op.f("ix_medications_patient_id"), "medications", ["patient_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_medications_patient_id"), table_name="medications")
    op.drop_index(op.f("ix_medications_consultation_id"), table_name="medications")
    op.drop_table("medications")
    op.drop_index(op.f("ix_consultations_patient_id"), table_name="consultations")
    op.drop_index(op.f("ix_consultations_consultation_date"), table_name="consultations")
    op.drop_table("consultations")
    op.drop_index(op.f("ix_patients_last_name"), table_name="patients")
    op.drop_index(op.f("ix_patients_first_name"), table_name="patients")
    op.drop_index(op.f("ix_patients_dni"), table_name="patients")
    op.drop_table("patients")
    # ### end Alembic commands ###
